apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lib-cameldemo-1-dmo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        customer: lib
        env: dmo
        app: cameldemo
    spec:
      containers:
        - name: connector
          image: eu.gcr.io/liberition/cameldemo:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "150m"
              memory: 512Mi
            limits:
              cpu: "250m"
              memory: 640Mi
